workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'  # Run CI/CD on all branches
stages:
  - build
  - test
before_script:
  - dotnet restore
build:
  stage: build
  script:
    - dotnet build --configuration Release
test:
  stage: test
  script:
    - dotnet test
